spring.application.name=finsecure


spring.datasource.url=jdbc:mysql://localhost:3306/finance_db
spring.datasource.username=root
spring.datasource.password=Root@123
spring.jpa.hibernate.ddl-auto=update



jwt.secret=pDPRmEDzYchxmJbUofaXYSK/r+4M4HGn+q5JwRBi2JE=
jwt.expiration=86400000
spring.jpa.open-in-view=false